language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

dist: xenial

sudo: required
services: xvfb

install:
  - ./py-wacz/.travis/install.sh

script:
  - ./py-wacz/.travis/test.sh

after_success:
  - codecov
